### ISSUE TITLE
enums in date-time fields

### ISSUE THREAD

**Issue by anttileppa** [starfishmod/WPAPI-SwaggerGenerator#6]
Generated JSON contains enums in date-time properties in definitions section (which causes client generations to fail). 

E.g. generated attachment:

```
definitions:
  attachment:
    type: object
    properties:
      date:
        description: 'The date the object was published, in the site''s timezone.'
        type: string
        format: date-time
        enum:
          - view
          - edit
          - embed
```
